description: 'Default Order PDF'
enabled: true
fileNameFormat: 'Order-{number}'
handle: order
isDefault: true
name: Default
sortOrder: 0
templatePath: buy/_pdf/order
uid: 6414b1d7-4091-420f-a175-16150e8df27d
