bcc: null
cc: null
enabled: true
name: 'Order Confirmation'
pdf: ce9b6388-7f97-4254-b64d-aea6551d1415
plainTextTemplatePath: ''
recipientType: customer
replyTo: null
subject: 'Order Confirmation - Bestellbestätigung'
templatePath: buy/_pdf/order
to: null
