field: 5385fca2-5efc-49e5-b179-b5ab4b79db2b
fieldLayouts:
  281bdc92-7034-45b1-a2b6-b0c7944d54fd:
    tabs:
      -
        elements:
          -
            fieldUid: 493f068d-3768-4510-b006-f1ea974baae6
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 54cc875d-eba4-4734-9940-8c16cf4f3d22
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a9be0a73-b3cc-45ce-a648-95e06bd32178
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a9cfc7a5-da1e-4be1-897b-94055842c85a
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0a8608fe-ece0-483c-8319-f1671c878999
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 900de470-c207-4528-88a6-c0c1f60687d8
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4aeb7cf2-d3ac-4cd5-9fce-3bba54fa3327
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0a8608fe-ece0-483c-8319-f1671c878999:
    contentColumnType: string(200)
    fieldGroup: null
    handle: buttonCaption
    instructions: 'If empty, the targets title will be used'
    name: 'Button Caption'
    searchable: true
    settings:
      byteLimit: null
      charLimit: 50
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  493f068d-3768-4510-b006-f1ea974baae6:
    contentColumnType: string(80)
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: 80
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  4aeb7cf2-d3ac-4cd5-9fce-3bba54fa3327:
    contentColumnType: text
    fieldGroup: null
    handle: backgroundImageData
    instructions: 'Will be ignored, if a reusable background color is selected'
    name: 'Background Image'
    searchable: false
    settings:
      assetSources:
        - images
        - shop
      data: null
      hasBlockImage: '1'
      sectionSources:
        - film
        - location
        - news
        - person
    translationKeyFormat: null
    translationMethod: none
    type: project\modules\main\fields\BackgroundImageField
  54cc875d-eba4-4734-9940-8c16cf4f3d22:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes:
        - 8136d7e9-1a74-464d-aef2-3a4f91a5cdda
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Custom.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  900de470-c207-4528-88a6-c0c1f60687d8:
    contentColumnType: string
    fieldGroup: null
    handle: reusableBackgroundColor
    instructions: ''
    name: 'Reusable Background Color'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Select a color'
      showSiteMenu: true
      source: null
      sources:
        - 'section:69f24ac1-fc43-498a-a08f-5ef30be4111d'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  a9be0a73-b3cc-45ce-a648-95e06bd32178:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda'
      singleUploadLocationSubpath: '{owner.section.handle|lower}{owner.folderName?''/''~owner.folderName:''''}'
      source: null
      sources:
        - 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a9cfc7a5-da1e-4be1-897b-94055842c85a:
    contentColumnType: string
    fieldGroup: null
    handle: buttonTarget
    instructions: 'Will only show if a text block is displayed.'
    name: 'Button Target'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: textImage
name: Text/Image
sortOrder: 1
