field: 5ff68d8e-e58c-4757-8b67-82b8d7831f0c
fieldLayout: 60c672c9-f1b2-4b85-913a-512dd005640c
instructions: 'Select 4 items, the first will be used for the background image and the teaser.'
name: 'Featured Section'
