fieldLayouts:
  7827d3c7-bca2-4938-9e29-2bac6a4e4514:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 9a302fae-a3bf-4298-8a06-24f8c8f6f335
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ac32d717-c9b4-4901-b342-7ed478344c89
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3ef62a7b-6c6d-470f-88a6-31de5a099b38
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 5385fca2-5efc-49e5-b179-b5ab4b79db2b
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1487a6e6-86d3-4c47-99eb-21f1e29e9494
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
handle: contentBuilder
hasTitleField: true
name: 'Content Builder'
section: 09f97fdd-45fe-4221-982a-a2077c8460b1
sortOrder: 2
titleFormat: ''
