fieldLayouts:
  714724b7-6adb-44f3-8b45-aed2bace9a45:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 9a302fae-a3bf-4298-8a06-24f8c8f6f335
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3ef62a7b-6c6d-470f-88a6-31de5a099b38
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 58b2e318-26cc-47b8-bee2-81369731d72f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
handle: eventsection
hasTitleField: true
name: Section
section: 011a8ede-f19a-4ed7-bb30-fdc9852a9c8b
sortOrder: 1
titleFormat: ''
