fieldLayouts:
  60c672c9-f1b2-4b85-913a-512dd005640c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 5ff68d8e-e58c-4757-8b67-82b8d7831f0c
            instructions: 'Select 4 items, the first will be used for the background image and the teaser.'
            label: 'Featured Section'
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: homeFeaturedSection
hasTitleField: false
name: 'Home Featured Section'
section: 0bc759f8-9766-4145-814c-570820748fe6
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
