contentColumnType: string
fieldGroup: 207a209a-820f-4db8-829a-e9b191ff1b54
handle: productFeaturedImage
instructions: ''
name: 'Product Featured Image'
searchable: false
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: ''
  restrictFiles: '1'
  selectionLabel: 'Select an image'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:caf05300-3e76-4a18-8567-e67a9099f462'
  singleUploadLocationSubpath: '{id}'
  source: null
  sources:
    - 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
