tabs:
  -
    fields:
      57d9965e-f781-474e-8cdc-0ed2b08c4128:
        required: false
        sortOrder: 1
      c207a853-622b-4b8f-b17a-bc4fcad5a676:
        required: false
        sortOrder: 2
    name: Content
    sortOrder: 1
  -
    fields:
      1028670c-180a-4f03-b010-3c268cb496aa:
        required: false
        sortOrder: 1
    name: Festival
    sortOrder: 2
