fieldLayouts:
  0363b002-87ed-4269-8dfe-e6bd956b3382:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: guide
hasUrls: true
name: Guide
settings:
  path: '@webroot/guide'
sortOrder: 3
type: craft\volumes\Local
url: '@web/guide'
