contentColumnType: text
fieldGroup: 17aa2ede-87b4-40b0-84d1-47a0b29e0b24
handle: address
instructions: ''
name: Address
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
