contentColumnType: text
fieldGroup: c177f5d7-6582-4202-a79c-a1e5bd7983a4
handle: background
instructions: ''
name: Background
searchable: true
settings:
  assetSources:
    - images
  data: null
  hasBlockImage: ''
  sectionSources:
    - film
    - news
    - person
translationKeyFormat: null
translationMethod: none
type: project\modules\main\fields\BackgroundImageField
