contentColumnType: text
fieldGroup: c2c0bc75-b1e1-470b-9373-d691afad3098
handle: bio
instructions: ''
name: Bio
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
