contentColumnType: text
fieldGroup: 5bd7b883-0d73-47f4-a7f4-bad70fe05acf
handle: body
instructions: ''
name: Body
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
