contentColumnType: string
fieldGroup: c2c0bc75-b1e1-470b-9373-d691afad3098
handle: firstName
instructions: ''
name: 'First Name'
searchable: true
settings:
  byteLimit: null
  charLimit: '30'
  code: ''
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
