contentColumnType: string
fieldGroup: f1d8d989-2bc0-4a0f-b58f-a348276a5596
handle: photo
instructions: ''
name: Photo
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: '1'
  restrictFiles: '1'
  selectionLabel: 'Select a photo'
  singleUploadLocationSource: 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda'
  singleUploadLocationSubpath: '{section.handle|lower}{folderName?''/''~folderName:''''}'
  source: null
  sources:
    - 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda'
  targetSiteId: null
  useSingleFolder: '1'
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
