contentColumnType: datetime
fieldGroup: 17aa2ede-87b4-40b0-84d1-47a0b29e0b24
handle: showtime
instructions: ''
name: Showtime
searchable: false
settings:
  minuteIncrement: '15'
  showDate: true
  showTime: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
