contentColumnType: string
fieldGroup: fea375f0-9f46-4952-b272-2dcf42b0cce5
handle: showInNav
instructions: ''
name: 'Show in Nav'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - 'Do not show'
        -
          - value
          - doNotShow
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Show in primary nav'
        -
          - value
          - primary
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Show in footer nav'
        -
          - value
          - footer
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
