contentColumnType: string
fieldGroup: fea375f0-9f46-4952-b272-2dcf42b0cce5
handle: siteName
instructions: ''
name: 'Site Name'
searchable: true
settings:
  byteLimit: null
  charLimit: '30'
  code: ''
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
