fieldLayouts:
  04741bab-c679-46e8-859c-8d9e491366c4:
    tabs:
      -
        fields:
          00ccae7e-39e6-498b-898c-afd6e2d9bebc:
            required: false
            sortOrder: 1
          cda59381-ba2c-462c-9ed9-314a86d072ea:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
handle: gdprInfo
name: GDPR
