fieldLayouts:
  56c0c6a2-134b-4466-be06-be33cddad846:
    tabs:
      -
        fields:
          10d8ae84-a8b6-489d-846d-1a7510cd9829:
            required: false
            sortOrder: 1
        name: SEO
        sortOrder: 1
handle: globalSeo
name: 'Global SEO'
