fieldLayouts:
  958d9c22-9855-40ef-b9cf-16af08de416b:
    tabs:
      -
        elements:
          -
            fieldUid: 64c37a78-14f3-4dba-874a-4d4bdd5ba1ee
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 84cd9d2e-97ae-44ff-91b1-26d8faedd358
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 986df256-f448-4273-95a5-acd9e4690eae
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2a586bbf-019e-4c87-bc15-d0b5db0efc98
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 83cdd527-ce90-4fb8-aca1-22382ad71e29
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3f9c2f2a-8ab0-4aba-bf4e-02d5336d14c0
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e43cbf9e-65e3-42de-a773-0efde519b772
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Site Info'
        sortOrder: 1
handle: siteInfo
name: 'Site Info'
