enableVersioning: true
handle: homeFeaturedSection
name: 'Home Featured Section'
previewTargets:
  -
    __assoc__:
      -
        - label
        - Home
      -
        - urlFormat
        - /
propagationMethod: all
siteSettings:
  97e0b749-86e3-49f1-918e-9b88758928f4:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  bbbb120d-5d71-4e7c-a164-487e401c4f2c:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
