enableVersioning: false
handle: language
name: Language
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  7e9d0ac6-02db-42c5-bfe5-2268b447b682:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  97e0b749-86e3-49f1-918e-9b88758928f4:
    enabledByDefault: true
    hasUrls: true
    template: _sections/category
    uriFormat: 'language/{slug}'
  bbbb120d-5d71-4e7c-a164-487e401c4f2c:
    enabledByDefault: true
    hasUrls: true
    template: _sections/category
    uriFormat: 'sprache/{slug}'
type: channel
