enableVersioning: true
handle: sitemap
name: Sitemap
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  97e0b749-86e3-49f1-918e-9b88758928f4:
    enabledByDefault: true
    hasUrls: true
    template: _sections/sitemap
    uriFormat: sitemap
  bbbb120d-5d71-4e7c-a164-487e401c4f2c:
    enabledByDefault: true
    hasUrls: true
    template: _sections/sitemap
    uriFormat: sitemap
type: single
